const express = require("express");
const app = express();
const cors = require("cors");
const authRouter = require("./routes/auth.routes");
require("dotenv").config();
require("./DBConnection.js")();
app.use(cors());
app.use(express.json());
app.use("/auth", authRouter);
app.listen(process.env.PORT);
